### ISSUE TITLE
SQL injection on chat

### ISSUE THREAD

**Issue by sylv0r** [hard-tech/fantasy-memory#142]
Be careful there is (maybe, I don't test) an SQL injection on your chat :
![image](https://github.com/hard-tech/fantasy-memory/assets/101133526/b1f86ae1-7a34-4e7d-8e92-5a38a73a486c)

Because you not check what inside the message 

Example, if a user put a message like :    aaa');  DROP TABLE messages; -- 

The SQL request will be :
 INSERT INTO messages (game_id, player_id, message) VALUES ( 1 , 1 ,'aaa');  DROP TABLE messages; -- 
 
 And it will delete your message table
 I'm not sure because cannot test, but be careful about this. And same for XSS injection on the chat.
 
 ;)

**Comment by sylv0r** [comment]
@vegasword @hard-tech @bourtitom

**Comment by hard-tech** [comment]
ok thanks we will change it before publish web site :)

**Comment by hard-tech** [comment]
normally sql injection is not done because the function is executed in two stages, prepare() then execute([]), which prevents sql injection and others.

**Comment by hard-tech** [comment]
if there was only execute() the sql injection would be done easily

**Comment by vegasword** [comment]
Actually we plan to replace our PHP code in several JavaScript files anyway, and I might crypt those files at the end of the project. Thanks to share your expertise @sylv0r ! 👍🏻
